services:
  - type: web
    name: leaf-diseases-detect
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
